global_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 100.0
  height: 100.0
  resolution: 0.05
  plugins:  
    - {name: map_layer, type: "costmap_2d::StaticLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
