local_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  plugins:
    - {name: no_go_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}




