 # Base calculator is used for calculating joint commands from velocity commands goven in the base_link frame, and for calculating odometry from actual joint states
base_calculator: "pltf_clc_std::PltfClcStd"
#base_calculator: "pltf_clc_2wdiff::PltfClc2WDiff"

# Motor drives
# type 0: propulsion/steering (default module)
# type 1: propulsion/propulsion (used for some diff. drive robots)
motor_drives:
  {
    drive0: {node: 1,
             x: -0.55, y: -0.3425,
             type: 0,
             leg_mesh: 0,
             r_wheel: 0.2, prp_gr_rt: 42, prp_enc_ppr: 1024, prp_max_rpm: 3000, prp_sim_a: 1.5,
             str_gr_rt: 42.8571429, str_enc_ppr: 1024, str_lim: 3.078027759, str_sim_v: 4},

    drive1: {node: 2,
             x: 0.55, y: -0.3425,
             type: 0,
             leg_mesh: 1,
             r_wheel: 0.2, prp_gr_rt: 42, prp_enc_ppr: 4096, prp_max_rpm: 3000, prp_sim_a: 1.5,
             str_gr_rt: 42.8571429, str_enc_ppr: 4096, str_lim: 3.078027759, str_sim_v: 4},
  
    drive2: {node: 3,
             x: 0.55, y:  0.3425,
             type: 0,
             leg_mesh: 2,
             r_wheel: 0.2, prp_gr_rt: 42, prp_enc_ppr: 1024, prp_max_rpm: 3000, prp_sim_a: 1.5,
             str_gr_rt: 42.8571429, str_enc_ppr: 1024, str_lim: 3.078027759, str_sim_v: 4},

    drive3: {node: 4,
             x: -0.55, y:  0.3425,
             type: 0,
             leg_mesh: 3,
             r_wheel: 0.2, prp_gr_rt: 42, prp_enc_ppr: 1024, prp_max_rpm: 3000, prp_sim_a: 1.5,
             str_gr_rt: 42.8571429, str_enc_ppr: 1024, str_lim: 3.078027759, str_sim_v: 4},
  }



# Battery enclosure modules. Set node to -1 if battery is not included in module.
batteries:
  {
    bat0: {node:  345, type: 1, x:  0.0, y:  0.285, z: 0.72, yaw: 0, bat_mesh: 0, with_battery: 1} ,
    bat1: {node: -1, type: 0, x:  0.0, y: -0.285, yaw: 0, z: 0.72, bat_mesh: 1, with_battery: 0},
  }

pipes:
  {
    pipe0: {x1: "-0.425", y1: "-0.285", x2: "0.425", y2: -0.30, height: 0.65, space: 0.15},
    pipe1: {x1: "0.425",  y1: "-0.285", x2: "0.425", y2: 0.30, height: 0.65, space: 0.15},
    pipe2: {x1: "0.425", y1: "0.285", x2: "-0.425", y2: 0.30, height: 0.65, space: 0.15},
    pipe3: {x1: "-0.425",  y1: "0.285", x2: "-0.425", y2: -0.30, height: 0.65, space: 0.15},
  }

corners:
  {
    corner0: {type: 0, corner_mesh: 0, x: "-0.425", y: "-0.285", z: 0.65, space: 0.15},
    corner1: {type: 1, corner_mesh: 0, x: "0.425", y: "-0.285", z: 0.65, space: 0.15},
    corner2: {type: 2, corner_mesh: 0, x: "0.425", y: "0.285", z: 0.65, space: 0.15},
    corner3: {type: 3, corner_mesh: 0, x: "-0.425", y: "0.285", z: 0.65, space: 0.15},
  }

# Beams connecting drive modules
beams:
  {
    #beam0: {start: "drive0", end: "drive1"},
    #beam1: {start: "drive1", end: "drive2"},
    #beam2: {start: "drive3", end: "drive2"},
    #beam3: {start: "drive0", end: "drive3"},
  }


########## Sensors ##########

# Lidars
lidar_front: {make: "sick",
              model: "nanoscan3",
              type: "2d",
              parent_link: "top1",
              topic_prefix: "scanner_front",
              suffix: "front",
              output_sim: "true",
              x: 0.34, y: -0.163, z: -0.034,
              roll: 0.0, pitch: 0.0, yaw: -0.795}

lidar_back: {make: "sick",
             model: "nanoscan3",
             type: "2d",
             parent_link: "top3",
             topic_prefix: "scanner_back",
             suffix: "back",
             output_sim: "true",
             x: 0.31, y: -0.154, z: -0.034,
             roll: 0.0, pitch: 0.0, yaw: -0.79}


# GNSS antennas - main antenna should be at the back
gnss_antenna_main: {x: -0.365, y: 0.307, z: 1.226,
                    parent_link: "base_link",
                    suffix: "back",
                    output_sim: "true"}

gnss_antenna_aux: {x: 0.365, y: -0.307, z: 1.215,
                   parent_link: "base_link",
                   suffix: "front",
                   output_sim: "false"} # Always false for aux antenna



# IMU
imu: {model: "um7",
      parent_link: "base_link",
      x: -0.03, y: 0.625, z: 0.67,
      roll: 0.0, pitch: 0.0, yaw: 0.0}


# Cameras
cameras: {camera1: {make: "basler",
                    model: "ac1440",
                    type: "2d",
                    parent_link: "corner2_2",
                    topic_prefix: "basler_ace1440_camera",
                    suffix: "0",
                    output_sim: "true",
                    x: 0.05, y: 0.0, z: 0.18,
                    roll: 0.0, pitch: 0.0, yaw: -1.5708}}
