global_costmap:
  update_frequency: 5.0
  publish_frequency: 0.5
  rolling_window: false
  static_map: true
  plugins:  
    - {name: map_layer, type: "costmap_2d::StaticLayer"}
    - {name: no_go_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
#    - {name: global_social_layer, type: "social_navigation_layers::ProxemicLayer", output: "screen"}
#    - {name: global_social_pass_layer, type: "social_navigation_layers::PassingLayer", output: "screen"}
