local_costmap:
#  global_frame: actor00/odom
#  robot_base_frame: actor00/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
#    - {name: local_social_layer, type: "social_navigation_layers::ProxemicLayer", output: "screen"}   # can you set inflation radius/cost scaling factor for this?
#    - {name: local_social_pass_layer, type: "social_navigation_layers::PassingLayer", output: "screen"}   # can you set inflation radius/cost scaling factor for this?





