# Author: Adam Binch
# email: adambinch@gmail.com

# include:                    boolean: you can turn a model on or off by setting include: 1 or include: 0, respectively
# pole_nx                     integer: number of poles aligned with the x-axis
# pole_ny                     integer: number of poles aligned with the y-axis (keep fixed at pole_ny: 5, if you want the canopy to fit)
# pole_dx                     float: distance between poles aligned with the x-axis (meters)
# pole_dy                     float: distance between poles aligned with the y-axis (meters) (keep fixed at pole_dy: 1.35, if you want the canopy to fit)
# pole_xoffset                float: sets the position of the poles along the x-axis (meters)
# pole_yoffset                float: sets the position of the poles along the y-axis (meters)
# arch_nx                     integer: number of arches 
# arch_dx                     float: distance between arches (meters)
# arch_xoffset                float: sets the position of the arches along the x-axis (meters)

# note: if you don't want the polytunnel to have a canopy set arch_nx: 0
# note: if you change the world name you will also have to change it in the launch file ../launch/world.launch (or make another launch file).


- world_name: 'riseholme.world'     

- polytunnel:
  - include: 1     # polytunnel 1
    fixed_arches: 1
    pole_nx: 9
    pole_ny: 5
    pole_dx: 2.94
    pole_dy: 1.32
    pole_xoffset: 7
    pole_yoffset: -6.64
    arch_nx: 17
    arch_dx: 1.53
    arch_xoffset: 6.72
    strut_positions: ['R']


  - include: 1     # polytunnel 2
    fixed_arches: 1
    pole_nx: 9
    pole_ny: 5
    pole_dx: 2.94
    pole_dy: 1.32
    pole_xoffset: 7
    pole_yoffset: 1.32
    arch_nx: 17
    arch_dx: 1.53
    arch_xoffset: 6.72
    strut_positions: ['L']


- frontage:
  - include: 1
    xpose: 0     
    ypose: 0
    yaw: 0

  - include: 1
    xpose: 37.95    
    ypose: -0.0075
    yaw: 3.1414


- riseholme_enclosure:
  - include: 1
    pose: [-2.83, -19.68, 0.0557]


- food_handling_unit:
  - include: 1
    pose: [-7.47, 1.67, 3.1414]


- lab:
  - include: 1
    pose: [-9.438, -45.426, 0.0]




