footprint: [[0.65, -0.38], [0.65, 0.38], [-0.60,0.38], [-0.6, -0.38]]  #rbsherpa std

# publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.3

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser rear_laser
  front_laser: 
    sensor_frame: $(arg prefix)front_laser_link
    data_type: LaserScan
    topic: $(arg front_scan_topic)
    marking: true
    clearing: true
  rear_laser: 
    sensor_frame: $(arg prefix)rear_laser_link
    data_type: LaserScan
    topic: $(arg rear_scan_topic)
    marking: true
    clearing: true

obstacle_camera_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_rgbd_to_scan
  front_rgbd_to_scan:
    data_type: LaserScan
    topic: $(arg front_rgbd_to_scan_topic)
    marking: true
    clearing: true
