local_costmap:
  global_frame: $(arg prefix)odom
  robot_base_frame: $(arg prefix)base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 7.0 
  height: 7.0 
  resolution: 0.05 
  
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: obstacle_laser_layer
      type: "costmap_2d::ObstacleLayer"
#    - name: obstacle_camera_layer
#      type: "costmap_2d::VoxelLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
